# -*- coding: utf-8 -*-
"""data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ScjNkyv_sOyjD0mxb-N9b_RG_9J6a3DN
"""

import pandas as pd
import re
import string
import emoji
import nltk
from nltk.corpus import stopwords
from datasets import load_dataset

# Télécharger stopwords
nltk.download('stopwords')

stopwords_fr = set(stopwords.words("french"))

def clean_text(text):
    text = str(text).lower()

    # Retirer URL
    text = re.sub(r"http\S+|www\S+", "", text)

    # Retirer emojis
    text = emoji.replace_emoji(text, replace="")

    # Retirer ponctuation
    text = text.translate(str.maketrans("", "", string.punctuation))

    # Garder lettres + chiffres
    text = re.sub(r"[^a-zàâäéèêëîïôöùûüç0-9\s]", " ", text)

    # Retirer stopwords
    text = " ".join([w for w in text.split() if w not in stopwords_fr])

    # Nettoyer espaces
    text = re.sub(r"\s+", " ", text).strip()

    return text


def label_sentiment(label):
    if label >= 3:
        return "positive"
    elif label < 2:
        return "negative"
    return "neutral"


def load_reviews(limit=1000):
    dataset = load_dataset(
        "SetFit/amazon_reviews_multi_fr",
        split=f"train[:{limit}]"
    )
    df = pd.DataFrame(dataset)
    df["texte_clean"] = df["text"].apply(clean_text)
    df["sentiment"] = df["label"].apply(label_sentiment)
    return df