# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJKa62hmUzpAL-ZYUXbeVeDfzmm5o3UW
"""

from fastapi import FastAPI
from pydantic import BaseModel
from generate_response import generer_reponse
from data_processing import clean_text, label_sentiment

app = FastAPI(title="API Analyse et Réponse Client")

class AnalyseRequest(BaseModel):
    texte: str

class AnalyseResponse(BaseModel):
    sentiment: str
    reponse: str

@app.post("/analyse", response_model=AnalyseResponse)
def analyse_avis(req: AnalyseRequest):
    # Nettoyer le texte
    texte_nettoye = clean_text(req.texte)

    # Déterminer le sentiment
    sentiment = label_sentiment(3 if "positive word" in texte_nettoye else 1)  # exemple ou adapter

    # Générer la réponse
    reponse = generer_reponse(req.texte)

    return AnalyseResponse(
        sentiment=sentiment,
        reponse=reponse
    )
    
