# -*- coding: utf-8 -*-
"""test_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o-3Dfb9mwjn4azR2-uPDx7ibB1vPo5z0
"""

from generate_response import generer_reponse

def test_generer_reponse_mock():
    import os
    os.environ["SKIP_MODEL_DOWNLOAD"] = "true"
    result = generer_reponse("Bonjour")
    assert "[MOCK]" in result